language: java

sudo: false

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - redis-server

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "EYxRjP/yBVPmDrv1MunXoZC/fwNVq8/oukKojwC2quxqwBsomX5qeXdfAiieJBlaFEM+PjMCweZ1wizWaPi/VMTFALsDrl2NbqPDM+aK6qlCgqmTyL3klVWKJMlXHh2eTSTbtapj/Giekud9OBComPABx+J8398f/aqlK4J+DPilaPwl40tXfVLdWSUu9bs6vNH/EgJyv/uCzZTVDusj9bLei63sFvPNJnDoC0Tojvl8LX6hDurgWBiL/vqxhEgjB+FxYQ71dkmlhn4oL2LYkBRwS2ac3simbcXth+c65u34lsSMtnSvkY7kR1crNK4H784ghuKhbTcVIRIXmXdhSJ/5qCs5Lj7EHQCyH3zwo/vmQGOD5FzpxJdTqCdXEQ0Cr9QsFOWBSQhAQdKuNbOPyZTIe+cjYhLJC3u0oaRK1I5+o8dEOm0vc4m25cDzazOX65ywXlzm0Hj9gwyIyF4fxWLlhrYiH3O5iYT9S1DVij2yygWcWWCWm1UpV69gANSVD00mmkGCBmDAdqGtj0sc/3Cm5zTrZaiGKCFLIx5a5YZeu608lJRRwW9cAYY8cexmO7pRgGnqvVCrdnR57g1gRAvOBfmhOnxvkKiNHG7ShNl+klGRex6RNi3bvVhbIMpBnYku84KKu//kSXP1RfIKSyHnKLO0Ow5bx1XAfdF1Fg4="