language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - docker
  - redis-server

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "EYxRjP/yBVPmDrv1MunXoZC/fwNVq8/oukKojwC2quxqwBsomX5qeXdfAiieJBlaFEM+PjMCweZ1wizWaPi/VMTFALsDrl2NbqPDM+aK6qlCgqmTyL3klVWKJMlXHh2eTSTbtapj/Giekud9OBComPABx+J8398f/aqlK4J+DPilaPwl40tXfVLdWSUu9bs6vNH/EgJyv/uCzZTVDusj9bLei63sFvPNJnDoC0Tojvl8LX6hDurgWBiL/vqxhEgjB+FxYQ71dkmlhn4oL2LYkBRwS2ac3simbcXth+c65u34lsSMtnSvkY7kR1crNK4H784ghuKhbTcVIRIXmXdhSJ/5qCs5Lj7EHQCyH3zwo/vmQGOD5FzpxJdTqCdXEQ0Cr9QsFOWBSQhAQdKuNbOPyZTIe+cjYhLJC3u0oaRK1I5+o8dEOm0vc4m25cDzazOX65ywXlzm0Hj9gwyIyF4fxWLlhrYiH3O5iYT9S1DVij2yygWcWWCWm1UpV69gANSVD00mmkGCBmDAdqGtj0sc/3Cm5zTrZaiGKCFLIx5a5YZeu608lJRRwW9cAYY8cexmO7pRgGnqvVCrdnR57g1gRAvOBfmhOnxvkKiNHG7ShNl+klGRex6RNi3bvVhbIMpBnYku84KKu//kSXP1RfIKSyHnKLO0Ow5bx1XAfdF1Fg4="

addons:
  sonarcloud:
    organization: "fartherp"
    token:
      secure: "LN14aataJhbmuRVyFf9jE70wREIg+HA5yttQcHeDAnCk9tsD41nDwpEN+jRuWDD3nRyesPgjam9VsVcSJViWQWFOCSn++UiqHFxQTuoy+iLqCysZ5eBRdXfMN3K1ZDPkjSA5xBXRzJzKPy/jn5VQLUaqSXT7HredLXyE7jhibh/a4XRnk77soYiLYxhJyNE2kfPXeh853I+voEfrdwACkrYw7O6vAX6/8a6gAtAzWYrwwQi5WIz1zNBUz6yndlXgo1ArPyFPu0VTKk25SczqIoTeC1r3rIoMPpIHsoNkYXgdrPlwxaiUk5g8k8OQiJaV/XWLQG4ms9fINcCWo6v0dFqoql8dyOWQSMZEN2SDI/pL/wWBKvz/hvqaUBaTjJBT+InMlIca5wseqvAOBg6cWpZ9oxVzjhDWPztbVx9iKw3tDVMyIdLVTWSRqeSDOOqyuwJhVzEmJMau7n68NfCz6FuUghvJsjewFZh+ncNpZJLglKOU9IXejp2KPWkvr6/5wtyHiS+TugfGaZAQjy/BzSeR9aohc+Ylwg/ICcBOd6ISmpyXRZ5oHBg7XEvmDDpMCteg6FWWh8EShDQM/faQFyy9jMiw26e9gki4JQ5DmZRvPCr1HhEQxxFsEplUAjUJD7UYuOB5GlbrRlDJsaEInuLDx4KnxoV/neHvRWAQf7E="